[package]
name = "tauri-plugin-rustore-pay"
version = "0.1.0"
edition = "2021"
links = "tauri-plugin-rustore-pay"

[build-dependencies]
tauri-plugin = { version = "2" }

[dependencies]
tauri = { version = "2", features = [] }

[lib]
name = "tauri_plugin_rustore_pay"
crate-type = ["lib", "cdylib", "staticlib"]
